### ISSUE TITLE
Allow UNIL and other university login

### ISSUE THREAD

**Issue by zifeo** [zifeo/Croque#4]
`categorie=shibboleth` (UNIL), `categorie=epfl-guests` (guest login)

**Comment by AlexConnat** [comment]
You don't want to organize inter-uni croques (for obvious logistical reasons)
Are/will the logic to create the assignments separated **per** university?

**Comment by zifeo** [comment]
We would need to have some location-based matching which is currently in progress. Let's try first to have independent and separate Croque running per university and then merge into a single platform if everything works as expected.
